package webSecondQuestion.jwt;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.Set;

/**
 *
 * @author Generated By Caracal Frameword, powered by Dr.Adldoost :D
 */
@Data
@NoArgsConstructor
public class JWTUserDetails {

    private String username;
    private Date creationDate;
    private Set<String> roles;
    private Set<String> permissions;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Set<String> getRoles() {
        return roles;
    }

    public void setRoles(Set<String> roles) {
        this.roles = roles;
    }

    public Set<String> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<String> permissions) {
        this.permissions = permissions;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getCif() {
        return cif;
    }

    public void setCif(String cif) {
        this.cif = cif;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    private String mobile;
    private String cif;
    private String customerId;

    public JWTUserDetails(String username, Date creationDate, Set<String> roles) {
        this.username = username;
        this.creationDate = creationDate;
        this.roles = roles;
    }

    public JWTUserDetails(String username, Date creationDate, Set<String> roles, String customerId, String mobile, String cif) {
        this.username = username;
        this.creationDate = creationDate;
        this.roles = roles;
        this.customerId = customerId;
        this.mobile = mobile;
        this.cif = cif;
    }
}
